# Image de base
FROM node:lts-alpine

# Répertoire de travail dans le conteneur
WORKDIR /home/node

# Copie des fichiers de configuration et des dépendances dans le conteneur
COPY package.json package-lock.json ./

# Installation des dépendances au moment du build pour éviter de les réinstaller à chaque changement de code
RUN npm install --legacy-peer-deps

# Copie du reste des fichiers de l'application
COPY . .

EXPOSE 3000

# Commande pour démarrer l'application en mode développement
CMD ["npm", "run", "start:dev"]