# Dans ce fichier de configuration, nous définissons un serveur virtuel pour rediriger les requêtes vers les services backend et frontend.

server {
    listen 80;

    location / {
        proxy_pass http://frontend:5173; # Redirige les requêtes vers le service frontend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Support WebSocket pour le live reload de Vite
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/ {
        proxy_pass http://backend:3000/; # Redirige les requêtes vers le service backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}