# Nom de la pipeline
name: CI/CD pipeline (Git Flow)

# Quand la pipeline se déclenche
on:
  push:
    branches:
    - main
    - develop
    - 'feature/**'
    - 'release/**'
    - 'hotfix/**'
  pull_request:
    branches:
    - main    # PR vers main depuis release ou hotfix 
    - develop # PR vers develope depuis feature

# Tâches à exécuter
jobs:
  test-and-build:
    name: Tests & Build
    runs-on: ubuntu-latest  

    # Etapes
    steps:

    # Téléchargement du code depuis GitHub
    - name: Checkout code
      uses: actions/checkout@v4 # Actions GitHub pour récupérer le code

    # Installer Node.js version 20
    - name: Setup Node.js
      uses: actions/setup-node@v4 # Actions GitHub pour installer Node.js
      with:
        node-version: '20'
    
    # Frontend

    # Installation des dépendances du frontend
    - name: Install Frontend
      working directory: ./frontend # Va dans le dossier frontend/
      run: npm ci # Installation

    # Vérification du code frontend avec ESLint
    - name: Lint Frontend
      working-directory: ./frontend
      run: npm run lint # Vérifie les erreurs de syntaxe

    # Compile le frontend
    - name: Build Frontend
      working-directory: ./frontend 
      run: npm run build # Compile TypeScript -> JS)

    # Backend

    # Installation des dépendances du backend
    - name: Install Backend
      working-directory: ./backend
      run: npm ci

    # Vérifie le code backend avec ESLint
    - name: Lint Backend
      working-directory: ./backend
      run: npm run lint

    # Compile le backend
    - name: Build Backend
      working-directory: ./backend
      run: npm run build

    